fingerprinting.json
See: https://app.asana.com/0/481882893211075/1199921872001518
=> Consolidate fingerprint lists into a JSON file

trackers-unprotected-temporary.txt
While we figure out what's breaking the view file page.
=> temp dropbox fix

trackers-unprotected-temporary.txt
=> Remove dropbox.com from temp unprotected list

fingerprinting.json
See https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/574
=> Add warzone.com to temp unprotected list due to canvas perf issues

fingerprinting.json
https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/574#issuecomment-803305735
=> Add skribbl.io to exempted Canvas protections

fingerprinting.json
See: https://app.asana.com/0/inbox/1199237043596759/1200129810868279/1200129810868292
=> Fingerprinting on shop sites breakage.

trackers-unprotected-temporary.txt
Report volume indicates something we're doing is causing breakage, unclear if login related or something else.
=> Add schwab.com to temp unprotected list

trackers-unprotected-temporary.txt
=> fredmeyer.com

trackers-unprotected-temporary.txt
I tested these and other kroger sites. It looks like they're having some intermittent issues serving images that are unrelated to blocking.
=> remove kroger sites

trackers-unprotected-temporary.txt
https://app.asana.com/0/569473074191537/1200221053445750/f
=> Adding x-kom.pl to safelist due to breakage on Safari and iOS

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/569473074191537/1200221053445750/f
=> Put x-kom.pl on both list and prepend with "www" for it to work on iOS/Safari.

fingerprinting.json, protections.json
See: https://app.asana.com/0/inbox/1199237043596759/1200216229834057/1200227129868486
=> Add chipotle.com whilst we investigate breakage

fingerprinting.json, protections.json
Fingerprinting protections are breaking login.
Internal task: https://app.asana.com/0/569473074191537/1200154425616676/f﻿
Github issue: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/616
=> Exception for pnc.com

fingerprinting.json, protections.json, trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/inbox/1199237043596759/1200216229834057/1200227129868486
=> Move chipotle to temp unprotected list

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/inbox/1199237043596759/1200234546296833/1200234868723082
=> Add Delta to the temp list

protections.json
**Asana:** https://app.asana.com/0/1198964220583541/1200253765918866/f
**Reviewer:** @jonathanKingston 
Adds `autofill` to the list of protections.
=> Add autofill to protections.json

trackers-unprotected-temporary.txt
Blocking prevents video playback
https://app.asana.com/0/1200277586140538/1200308819111409/f
=> Temp allow sbs.com.au

trackers-unprotected-temporary.txt
Breakage due to adblocker wall on iOS
https://app.asana.com/0/1200277586140538/1200336080961482/f
=> Exception for sportskeeda.com

protections.json
For:
https://app.asana.com/0/inbox/1199237043596759/1200345617254244/1200364803080726
https://app.asana.com/0/inbox/1199237043596759/1200363682315256/1200355036498932
=> Audio debugging for reports

protections.json
For performance issues: https://app.asana.com/0/inbox/1199237043596759/1200395885552112/1200378187834561
=> Add coolmathgames to protections.json

trackers-unprotected-temporary.txt
https://app.asana.com/0/inbox/1199237043596759/1200367164996851/1200410034828377
=> Add www.usajobs.gov

trackers-unprotected-temporary.txt
Some missing images on the site
=> add spiegel.de

trackers-unprotected-temporary.txt
- tentree.com main page is broken
- dyson.com broken checkout process
=> Add dyson and tentree

protections.json
See relevant issues of their inclusion:
- https://github.com/duckduckgo/content-blocking-lists/pull/31
- https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/610
Removing now we have fixed the root cause.
=> Remove text overrides for canvas

protections.json
https://app.asana.com/0/1200277586140538/1200451609115525
=> Remove cookie protection whilst on hangouts.google.com due to breakage

trackers-unprotected-temporary.txt
https://app.asana.com/0/1200277586140538/1200457612497886
=> Adding 6play.fr for breakage reports

protections.json
https://app.asana.com/0/569473074191537/1200478549505525/f
=> Temp adding google docs for breakage

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/1200277586140538/1200291944240425/f
=> Adding www.merriam-webster.com due to tracker wall breakage on iOS

trackers-unprotected-temporary.txt
https://app.asana.com/0/inbox/1199237043596759/1200518097540265/1200518396544087
=> Adding John Lewis to the temp list due to critical breakage

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/569473074191537/1200216229834057/f
=> Remove Chipotle from temp list as breakage has gone.

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
Breakage fixed by blocklist changes: https://app.asana.com/0/1200223097357040/1200308819111409/f
=> Remove sbs.com.au

protections.json, trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/1200223097357040/1200234546296833
=> Move temp list for delta to canvas temp list

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/312629933896096/1200327303839559/f
=> Remove reuters.com as moatads are no longer causing an issue here.

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/1200223097357040/1200546471549589/f
=> Adding rp5.ru to the temporary list due to a hard blocking wall

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
- https://app.asana.com/0/1200223097357040/1200556293839196/f
- https://app.asana.com/0/1200223097357040/1200557343771712/f
=> Temp allow stubhub.com and channel4.com

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
Removals based on the July blocklist update: https://app.asana.com/0/1200342317600122/1200437897060097
=> Remove sites that are moved to the blocklist

protections.json
For citi breakage and other reported websites: https://app.asana.com/0/892838074342800/1200567415715184
=> Disable audio protection whilst slowdown is investigated

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
Adding tiaa.org, joinhoney.com, expedia.com, and battle.net for broken login reports
=> Add sites reported for broken logins

protections.json
https://app.asana.com/0/1200277586140538/1200491496106209/f
=> Disable canvas protection on textfree.us

trackers-unprotected-temporary.txt
https://app.asana.com/0/1200277586140538/1200609154929157/f
=> Prune batch of permanently broken sites

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
Reverts duckduckgo/content-blocking-lists#66
The blocklist has been updated to resolve the breakage on these sites.
=> Revert "Add sites reported for broken logins"

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/1200223097357040/1200617876677506/f
=> Add fidelity.com

trackers-unprotected-temporary.txt, trackers-whitelist-temporary.txt
https://app.asana.com/0/1200223097357040/1200371396317346/f
=> Remove ca.gov
